version: "3.4"

services:
  # descrevendo o serviço do banco de dados da aplicação
  banco:
    image: mysql:5.7
    container_name: banco
    ports:
      - "3306:3306"
    # Carregando o plugin de autenticação do mysql
    command: --default-authentication-plugin=mysql_native_password
    # Definindo as variáveis de ambiente que informam o nome do banco de dados a ser criado, a senha root, além do usuário e senha do banco
    environment:
      MYSQL_ROOT_PASSWORD: agenda
      MYSQL_DATABASE: agenda
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./data:/var/lib/mysql
      - ./site/pessoa.sql:/docker-entrypoint-initdb.d/pessoa.sql
    networks: 
      - site-network
  
  # Descrevendo o serviço gerenciador da aplicação
  web:
    image: nginx:latest
    container_name: aplicacao
    ports:
      - "8080:80"
    volumes: 
      - ./site:/site
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - site-network

  # Descrevendo o web site da aplicação
  php:
    image: php-pdo-treinamento
    container_name: php
    volumes: 
      - ./site:/site
    networks: 
      - site-network

# Criando a rede "site-networks"
networks:
  site-network:
    driver: bridge